Repository observernet/obsr, pull requests merged in 2019-03, with the labels that each got.

#28 [gui][bug] fix to display missing clock5.png tx image
  src/qt/transactiontablemodel.cpp
Labels: bug, gui

#29 [tests] - enable feature_minchainwork.py and interface_zmq.py in test_runner.py
  test/functional/test_runner.py
Labels: tests

#27 [tests][bug] updated minchainwork and interface_zmq python scripts
  test/functional/feature_minchainwork.py
  test/functional/interface_zmq.py
Labels: bug, tests

#31 release 1.1.00
  contrib/seeds/README.md
  contrib/seeds/makeseeds.sh
  src/chainparams.cpp
  src/chainparamsseeds.h
  src/qt/forms/tradingdialog.ui
  src/qt/walletframe.h
  src/version.h
Labels: needs release notes
